# Generated by Django 3.1.3 on 2020-11-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullnme',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
