# Generated by Django 3.1.3 on 2020-11-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_user_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullnme',
            new_name='full_name',
        ),
    ]
