# Generated by Django 3.1.3 on 2020-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(blank=True, max_length=200, null=True)),
                ('mcDispatchNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('mcMembershipNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('PoNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('mcCoverageAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('customerName', models.CharField(blank=True, max_length=200, null=True)),
                ('customerPhone', models.CharField(blank=True, max_length=200, null=True)),
                ('customerEmail', models.EmailField(blank=True, max_length=200, null=True)),
                ('customerAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('pickupLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('dropLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('milesToVeh', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('milesTowed', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('vehLicence', models.CharField(blank=True, max_length=200, null=True)),
                ('vehLicenceState', models.CharField(blank=True, max_length=200, null=True)),
                ('vehVin', models.CharField(blank=True, max_length=200, null=True)),
                ('vehYear', models.CharField(blank=True, max_length=200, null=True)),
                ('vehMake', models.CharField(blank=True, max_length=200, null=True)),
                ('vehModel', models.CharField(blank=True, max_length=200, null=True)),
                ('vehColor', models.CharField(blank=True, max_length=200, null=True)),
                ('vehOdom', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('billingNotes', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_audited', models.BooleanField(default=True)),
                ('driver', models.CharField(blank=True, max_length=200, null=True)),
                ('truck', models.CharField(blank=True, max_length=200, null=True)),
                ('re', models.DateTimeField()),
                ('di', models.DateTimeField()),
                ('er', models.DateTimeField()),
                ('ol', models.DateTimeField()),
                ('cl', models.DateTimeField()),
            ],
        ),
    ]
