# Generated by Django 3.1.3 on 2020-11-30 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_service_slug'),
        ('calls', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.Service'),
        ),
        migrations.AddField(
            model_name='call',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='call',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
